name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: sparkfabrik/android-build-action@v1.3.4
      with:
        project-path: .
        output-path: faceguard.apk
        ruby-version: "2.7.5"
        bundler-version: "2.3.26"    
